---
title: "Statistical Tests in R"
author: "yilin"
date: "2021/11/20"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document:
    latex_engine: xelatex
---
#**Part0 table1**
```{r include=T}
library(table1)
library(boot)
melanoma2 <- melanoma
melanoma2$status <- 
  factor(melanoma2$status, 
         levels=c(2,1,3),
         labels=c("Alive", # Reference
                  "Melanoma death", 
                  "Non-melanoma death"))
table1(~ factor(sex) + age + factor(ulcer) + thickness | status, data=melanoma2)
melanoma2$sex <- 
  factor(melanoma2$sex, levels=c(1,0),
         labels=c("Male", 
                  "Female"))
 
melanoma2$ulcer <- 
  factor(melanoma2$ulcer, levels=c(0,1),
         labels=c("Absent", 
                  "Present"))

label(melanoma2$sex)       <- "Sex"
label(melanoma2$age)       <- "Age"
label(melanoma2$ulcer)     <- "Ulceration"
label(melanoma2$thickness) <- "Thickness"

units(melanoma2$age)       <- "years"
units(melanoma2$thickness) <- "mm"

table1(~ sex + age + ulcer + thickness | status, data=melanoma2, overall="Total")
```

```{r }
labels <- list(
    variables=list(sex="Sex",
                   age="Age (years)",
                   ulcer="Ulceration",
                   thickness="Thickness (mm)"),
    groups=list("", "", "Death"))

# Remove the word "death" from the labels, since it now appears above
levels(melanoma2$status) <- c("Alive", "Melanoma", "Non-melanoma")
strata <- c(list(Total=melanoma2), split(melanoma2, melanoma2$status))
my.render.cont <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=3), c("",
        "Mean (SD)"=sprintf("%s &plusmn; %s", MEAN, SD)))
}
my.render.cat <- function(x) {
    c("", sapply(stats.default(x), function(y) with(y,
        sprintf("%d (%0.1f %%)", FREQ, PCT))))
}

table1(strata, labels, groupspan=c(1, 1,2),
       render.continuous=my.render.cont, render.categorical=my.render.cat)

```

```{r }
f <- function(x, n, ...) factor(sample(x, n, replace=T, ...), levels=x)
set.seed(427)

n <- 146
dat <- data.frame(id=1:n)
dat$treat <- f(c("Placebo", "Treated"), n, prob=c(1, 2)) # 2:1 randomization
dat$age   <- sample(18:65, n, replace=TRUE)
dat$sex   <- f(c("Female", "Male"), n, prob=c(.6, .4))  # 60% female
dat$wt    <- round(exp(rnorm(n, log(70), 0.23)), 1)

# Add some missing data
dat$wt[sample.int(n, 5)] <- NA

label(dat$age)   <- "Age"
label(dat$sex)   <- "Sex"
label(dat$wt)    <- "Weight"
label(dat$treat) <- "Treatment Group"

units(dat$age)   <- "years"
units(dat$wt)    <- "kg"
table1(~ age + sex + wt | treat, data=dat)
table1(~ age + sex + wt | treat, data=dat, overall=F)
table1(~ age + wt | sex*treat, data=dat)
table1(~ age + wt | treat*sex, data=dat,render.continuous=my.render.cont, render.categorical=my.render.cat)
##
dat$dose <- (dat$treat != "Placebo")*sample(1:2, n, replace=T)
dat$dose <- factor(dat$dose, labels=c("Placebo", "5 mg", "10 mg"))

strata <- c(split(dat, dat$dose), list("All treated"=subset(dat, treat=="Treated")), list(Overall=dat))

labels <- list(
    variables=list(age=render.varlabel(dat$age),
                   sex=render.varlabel(dat$sex),
                   wt=render.varlabel(dat$wt)),
    groups=list("", "Treated", ""))
table1(strata, labels, groupspan=c(1, 3, 1))
```


```{r }
library(MatchIt) 
library(tidyverse)
data(lalonde)
head(lalonde)
lalonde<-lalonde %>% 
  mutate(across(c(treat,married,nodegree),as.factor))

metadata <- list(
  labels=list(
    race = "Race",
    married = "Married",
    nodegree = "No high school diploma",
    age  = "Age",
    re74 = "1974 Income",
    re75 = "1975 Income",
    re78 = "1978 Income"),
  units=list(
    age = "years"),
  categoricals=list(
    treat = list(
      `0` = "Control",
      `1` = "Treat"),
    married=list(`0` = "No",
      `1` = "Yes"),nodegree=list(`0` = "FALSE",
      `1` = "TRUE")))
data=t1read(lalonde,metadata)
pvalue <- function(x, ...) {
    # Construct vectors of data y, and groups (strata) g
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y)) {
        # For numeric variables, perform a standard 2-sample t-test
        p <- t.test(y ~ g)$p.value
    } else {
        # For categorical variables, perform a chi-squared test of independence
        p <- chisq.test(table(y, g))$p.value
    }
    # Format the p-value, using an HTML entity for the less-than sign.
    # The initial empty string places the output on the line below the variable label.
    c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}
a<-table1(~ age + race + married + nodegree + re74 + re75 + re78 | treat,
    data=data, render.continuous=my.render.cont, render.categorical=my.render.cat,overall=F, extra.col=list(`P-value`=pvalue))
b<-table1(~ age + race + married + nodegree + re74 + re75 + re78,
    data=data, render.continuous=my.render.cont, render.categorical=my.render.cat,overall=T)
a<-as.data.frame(a)
##write_xlsx(..,"C:/Users/....xlsx")
```

```{r include=T}
pvalue <- function(x, ...) {
    # Construct vectors of data y, and groups (strata) g
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y)) {
        # For numeric variables, perform a standard 2-sample t-test
        p <- oneway.test(y ~ g)$p.value
    } else {
        # For categorical variables, perform a chi-squared test of independence
        p <- chisq.test(table(y, g))$p.value
    }
    # Format the p-value, using an HTML entity for the less-than sign.
    # The initial empty string places the output on the line below the variable label.
    c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}
data=t1read(lalonde,metadata)
table1(~ age + race + married + nodegree + re74 + re75 + re78+ treat |race,data=data, render.continuous=my.render.cont, render.categorical=my.render.cat,overall=F, extra.col=list(`P-value`=pvalue))

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
